In [1]:
import sys
sys.path.append('../../Simulate/')
import importlib

from StreamReads import StreamReads
from StreamHTSIM import StreamHTSIM

In [2]:
working_path = "/home/wbguo/iproject/BSReadSim/test/"
ref_fasta = working_path + 'data/ref/BSB_test.fa'
outdir = working_path + "outdir/"

In [3]:
htsim_arg= ['/home/wbguo/iproject/BSReadSim/HTSIM/htsim']

sim_dict = {'-N':1000, 
            '-h':0, 
            '-T':0,
            '-1':100, 
            '-2':100,
            '-e':0.005,
            '-i':400,
            '-I':25,
            '-r':0.001, 
            '-R':0.15,
            '-X':0.15, 
            '-A':0.05,
            '-f':1,
           }

In [4]:
sim_sub = htsim_arg + [str(item) for key_val in sim_dict.items() for item in key_val]

sim_cmd =  sim_sub + [ref_fasta]

In [5]:
i = 0
for variant_contig, sim_data in StreamHTSIM(sim_cmd):    
    if variant_contig:
        print(variant_contig)
        continue
    if not variant_contig:
        i +=1
#     if i > 2:
#         print(i)
#         break
    if len(sim_data[0]['seq']) != len(sim_data[0]['ctx']) or len(sim_data[1]['seq']) != len(sim_data[1]['ctx']):
        break

Simulating whole genome reads:
Reference genome file: /home/wbguo/iproject/BSReadSim/test/data/ref/BSB_test.fa
[main] Calculating the total length and effective length of the reference sequences...
[main] Found 6 contig sequences, total length: 1961600, effective length: 1961600
[main] No contig id specified, will generate 1000 reads from all contigs
[main] No VCF input, will generate SNP randomly if mutation rate is nonzero
[htsim] seed = 1677576010
[sim_core] contig 'chr10': simulate 215 reads...
[sim_core] contig 'chr11': simulate 216 reads...
[sim_core] contig 'chr12': simulate 214 reads...
[sim_core] contig 'chr13': simulate 171 reads...


chr10
chr11
chr12
chr13
chr14
chr15


[sim_core] contig 'chr14': simulate 179 reads...
[sim_core] contig 'chr15': simulate 2 reads...
[sim_core] Generated 997 read pairs, with 105 contain SNP, 22 contain INDEL


In [6]:
i

997

In [7]:
sim_data

[{'read_id': '@chr15:173:594:1',
  'pair': 0,
  'strand': -1,
  'flag_pos': 1,
  'flag_mut': 65378,
  'flag_indel': 0,
  'start': 172,
  'end': 272,
  'cover_pos': 1,
  'n_sub': 1,
  'n_indel': 0,
  'insert_size': 421,
  'inner_dist': 221,
  'cgr': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
  'seq': array([1, 3, 0, 0, 0, 3, 0, 1, 0, 2, 1, 0, 2, 0, 0, 2, 2, 1, 0, 3, 0, 0,
         2, 0, 0, 0, 0, 3, 1, 0, 2, 0, 3, 1, 0, 1, 0, 0, 0, 0, 3, 0, 3, 0,
         0, 0, 1, 0, 3, 2, 2, 0, 3, 2, 0, 1, 0, 2, 0, 3, 1, 3, 1, 0, 3, 0,
         2, 0, 1, 3, 3, 0, 0, 0, 1, 1, 0, 3, 0, 0, 0, 1, 0, 2, 0, 2, 1, 1,
         3, 2, 1, 1, 3, 0, 0, 2, 0, 1, 3, 0], dtype=int8),
  'ofs': array([0, 0, 0, 0, 

In [8]:
''.join(['ACGT'[i] for i in sim_data[0]['seq']])

'CTAAATACAGCAGAAGGCATAAGAAAATCAGATCACAAAATATAAACATGGATGACAGATCTCATAGACTTAAACCATAAACAGAGCCTGCCTAAGACTA'

In [9]:
''.join(['ACGT'[i] for i in sim_data[1]['seq']])

'GGGAGTGGGGTTTTAATGTGACAGGATTCATTGGGGTGAGCTCCATCCCAGGTAAAATCAGGGCCTTCAGTATATCCATCACTGGAGCAATATACATTGT'

In [10]:
import numpy as np

x = np.array([i in (1,2) for i in sim_data[0]['seq']])
y = np.logical_not(sim_data[0]['ctx'].mask)

In [11]:
x

array([ True, False, False, False, False, False, False,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False,  True, False, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False, False,  True, False,  True,
       False, False, False,  True, False,  True, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True, False, False, False,  True, False,  True, False,
       False])

In [12]:
y

array([ True, False, False, False, False, False, False,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False,  True, False, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False, False,  True, False,  True,
       False, False, False,  True, False,  True, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True, False, False, False,  True, False,  True, False,
       False])

In [13]:
np.logical_xor(x, y)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [14]:
import numpy as np
a = np.array([0,0,1,1,2])
u, c = np.unique(a, return_counts=True)
dup = u[c > 1]

In [15]:
u

array([0, 1, 2])

In [16]:
c

array([2, 2, 1])

In [17]:
dup

array([0, 1])

In [18]:
sim_data[0]['seq'].flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [19]:
sim_data[0]['ctx'].flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [20]:
sim_data[0]['cgr'].flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [21]:
sim_data[0]['ofs'].flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [22]:
sim_data[0]['ctx'].flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# if changed reload

In [23]:
import StreamReads
importlib.reload(StreamReads)
from StreamReads import StreamReads

In [28]:
import pickle

with open('/home/wbguo/iproject/BSReadSim/test/data/test_read_pair.pickle', 'rb') as handle:
    read_pair = pickle.load(handle)

In [29]:
fastq_out = StreamReads(outdir=outdir, prefix="sim", pair_end=True)

../../Simulate/StreamReads.py:38: UserWarning: Fastq file exists, will overwrite... /home/wbguo/iproject/BSReadSim/test/outdir//sim_1.fastq
  warnings.warn(f'Fastq file exists, will overwrite... {fastq_file}')
../../Simulate/StreamReads.py:38: UserWarning: Fastq file exists, will overwrite... /home/wbguo/iproject/BSReadSim/test/outdir//sim_2.fastq
  warnings.warn(f'Fastq file exists, will overwrite... {fastq_file}')


In [30]:
fastq_out.output_reads(read_pair, 0, 0)

In [31]:
fastq_out.close()