In [1]:
import numpy as np

# masked array

In [2]:
x = np.arange(10)

In [3]:
m = np.ma.masked_array(x, x>5)

In [4]:
m

masked_array(data=[0, 1, 2, 3, 4, 5, --, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True,  True],
       fill_value=999999)

In [5]:
m+1

masked_array(data=[1, 2, 3, 4, 5, 6, --, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True,  True],
       fill_value=999999)

# size compared to normal array

In [6]:
import sys
sys.getsizeof(m)

128

In [7]:
sys.getsizeof(x)

184

# operations

In [8]:
np.bitwise_and(m+1, 0x1)

masked_array(data=[1, 0, 1, 0, 1, 0, --, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True,  True],
       fill_value=999999)

In [9]:
m & x

masked_array(data=[0, 1, 2, 3, 4, 5, --, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True,  True],
       fill_value=999999)

In [10]:
np.sum(np.logical_not(m.mask))

6

In [11]:
np.bitwise_and(m+1, 0x1)

masked_array(data=[1, 0, 1, 0, 1, 0, --, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True,  True],
       fill_value=999999)

# strange behavior with np.where

In [12]:
np.where(np.bitwise_and(m+1, 0x1))

(array([0, 2, 4, 7, 9]),)

In [13]:
np.where(np.bitwise_and(m+1, 0x1)==1)

(array([0, 2, 4]),)

In [14]:
np.where(np.array([0,1,-1,0,100]))

(array([1, 2, 4]),)

# test class method's variable scope

In [14]:
class s:
    def __init__(self):
        self.x = 10
        self.y = 5
        self.z = {1:10, 2:5}
        
    def func(self):
        my_list = [{1:10, 2:5}, {10:10, 5:5}]
        print(my_list)
        self.func2(my_list)
        print(my_list)
        self.func3(my_list[0])
        print(my_list)
    
    def func2(self, my_list):
        my_list[0][3] = 3.33
        print(my_list)
    
    def func3(self, my_dict):
        my_dict[3] = 1
        print(my_dict)

In [15]:
t = s()

In [16]:
t.func()

[{1: 10, 2: 5}, {10: 10, 5: 5}]
[{1: 10, 2: 5, 3: 3.33}, {10: 10, 5: 5}]
[{1: 10, 2: 5, 3: 3.33}, {10: 10, 5: 5}]
{1: 10, 2: 5, 3: 1}
[{1: 10, 2: 5, 3: 1}, {10: 10, 5: 5}]


# slicing

In [17]:
y = np.arange(10)

In [18]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:0]

array([], dtype=int64)

In [21]:
y[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.concatenate((x[:0], y[0:]),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[np.where(y==10)] +=1

In [26]:
x[-1:]

array([9])

In [27]:
from scipy.stats import bernoulli

In [28]:
bernoulli.rvs([0.1], size=0)

array([], dtype=int64)

# translate

In [20]:
arr = np.array([0,1,2,3]*30)

In [21]:
arr

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
       0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
       0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [22]:
%timeit ''.join('ACGT'[i] for i in arr)

17.9 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
''.join('ACGT'[i] for i in arr)

'ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT'