In [7]:
from select import select
from subprocess import Popen, PIPE
import numpy as np

while True:
    child = Popen('echo hello; echo goodbye>&3', shell=True, stdout=PIPE, stderr=PIPE)
    rfs, x, y = select([child.stdout, child.stderr], [], [])
    child.wait()
    if len(rfs) > 1:
        print('Data available on both pipes simultaneously! Cannot interleave correctly.')
        break

Data available on both pipes simultaneously! Cannot interleave correctly.


In [5]:
from Bio import SeqIO
reference_file = "/home/wbguo/iproject/BSBolt/tests/TestData/BSB_test.fa"

In [6]:
reference_dict = SeqIO.to_dict(SeqIO.parse(reference_file, "fasta"))

In [9]:
reference_dict["chr10"][1:2]

SeqRecord(seq=Seq('C'), id='chr10', name='chr10', description='chr10', dbxrefs=[])

In [24]:
base_info = '0_0,6_0,20_0,28_0,38_0,40_0,43_0,44_0,45_0,47_0,49_0,51_0,53_0,56_0,61_0,65_0,66_0,67_0,72_0,78_0,84_0,'

In [30]:
np.array([i.split("_") for i in base_info.split(",")[:-1]]).transpose().astype(int)[0]

array([ 0,  6, 20, 28, 38, 40, 43, 44, 45, 47, 49, 51, 53, 56, 61, 65, 66,
       67, 72, 78, 84])

In [32]:
a = np.array([1,1,1,1])

In [33]:
b = np.array([-1,0,1,2])

In [34]:
c = 100 + a + b

In [35]:
c

array([100, 101, 102, 103])

In [52]:
seq = 'ACTTTTTCTGTCTCATATTTGCTTAAATCTGTAAAACACATATGGATGGGAAACCACTGAATAATGTAAATCCTGCCTCGGCCTCCCAAAGTGCTGGGAT'

In [136]:
str(seq[1:3])

"['C' 'T']"

In [83]:
cigar = 'MMMMMMMMMMMMMMMMXMMIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'

In [96]:
seq_array = np.array(list(seq))
cigar_array = np.array(list(cigar))

In [90]:
np.where((cigar_array == "X") | (cigar_array == "I"))[0]

array([16, 19])

In [56]:
cigar_array

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M'], dtype='<U1')

In [94]:
len(cigar_array[[1,2]])

2

In [120]:
np.random.beta(1,1,size =1)[0]

0.5113362827575434

In [82]:
import re
[m.start(0) for m in re.finditer("C", str(reference_dict["chr10"].seq))]
[m.start(0) for m in re.finditer("G", str(reference_dict["chr10"].seq))]

[4,
 11,
 13,
 14,
 25,
 31,
 33,
 40,
 42,
 53,
 68,
 77,
 78,
 88,
 90,
 93,
 94,
 95,
 100,
 101,
 103,
 105,
 110,
 113,
 114,
 115,
 117,
 126,
 127,
 128,
 129,
 130,
 132,
 133,
 143,
 152,
 153,
 171,
 181,
 184,
 187,
 188,
 194,
 202,
 221,
 222,
 225,
 229,
 238,
 255,
 257,
 261,
 267,
 277,
 278,
 283,
 291,
 293,
 297,
 303,
 308,
 310,
 316,
 319,
 320,
 322,
 324,
 325,
 326,
 327,
 335,
 336,
 338,
 342,
 343,
 345,
 346,
 350,
 351,
 354,
 356,
 373,
 383,
 384,
 389,
 393,
 394,
 396,
 405,
 409,
 413,
 418,
 419,
 426,
 427,
 429,
 431,
 457,
 463,
 464,
 470,
 473,
 476,
 478,
 481,
 493,
 494,
 495,
 497,
 499,
 500,
 501,
 502,
 510,
 512,
 516,
 517,
 525,
 526,
 527,
 528,
 530,
 532,
 543,
 544,
 553,
 554,
 555,
 562,
 576,
 577,
 579,
 591,
 606,
 616,
 618,
 619,
 631,
 636,
 642,
 643,
 650,
 654,
 660,
 661,
 665,
 676,
 686,
 694,
 708,
 709,
 713,
 723,
 728,
 729,
 739,
 740,
 743,
 745,
 746,
 749,
 757,
 759,
 760,
 762,
 763,
 765,
 768,
 786,
 790,

In [80]:
len(reference_dict["chr10"])

423500

In [131]:
str(reference_dict["chr10"][1:3].seq)

'CT'

In [91]:
from scipy.stats import bernoulli

In [100]:
sequencing_error = 0.005
np.array(bernoulli.rvs(sequencing_error, size = len(seq_array)))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [110]:
random.sample(['A','C','T'].remove('A'), 1)

TypeError: Population must be a sequence or set.  For dicts, use list(d).

In [116]:
x = ['A','C','T']

In [117]:
y = x.remove('A')

In [118]:
x

['C', 'T']