In [1]:
from scipy.stats import bernoulli

def fetch_meth_state(read_meth):
    '''set methylation states based on the meth_arr'''
    meth_states = np.zeros(read_meth.size)
    nonzero_idx = np.where(read_meth)[0]    # this returns a tuple
    meth_states[nonzero_idx] = bernoulli.rvs(read_meth[nonzero_idx], size = nonzero_idx.size)
    return meth_states

def fetch_meth_state2(read_meth):
    return np.random.random(size = read_meth.size) < read_meth

In [2]:
import numpy as np
import random

read_meth   = np.zeros(150)
num_nonzero = 20
nonzero_idx = random.sample(range(150), num_nonzero)
read_meth[nonzero_idx] = [ random.random() for _ in range(num_nonzero)]

In [3]:
read_meth

array([0.44411496, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.82351217, 0.        , 0.0878294 ,
       0.        , 0.63286859, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.55075418, 0.        , 0.        , 0.        , 0.32871533,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.23380493, 0.        , 0.34658764, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.12215688,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [4]:
%timeit fetch_meth_state(read_meth)

192 µs ± 349 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit fetch_meth_state2(read_meth)

6.3 µs ± 20.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
fetch_meth_state(read_meth)

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
fetch_meth_state2(read_meth)

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,

In [13]:
list1 = []
list2 = []

for i in range(10000):
    list1.append(fetch_meth_state(read_meth).sum())
    list2.append(fetch_meth_state2(read_meth).sum())

[10.0,
 8.0,
 9.0,
 10.0,
 6.0,
 9.0,
 11.0,
 13.0,
 6.0,
 10.0,
 9.0,
 11.0,
 12.0,
 9.0,
 8.0,
 9.0,
 6.0,
 7.0,
 11.0,
 10.0,
 8.0,
 9.0,
 7.0,
 11.0,
 7.0,
 9.0,
 11.0,
 11.0,
 10.0,
 8.0,
 9.0,
 11.0,
 8.0,
 12.0,
 11.0,
 7.0,
 11.0,
 9.0,
 7.0,
 10.0,
 5.0,
 9.0,
 8.0,
 9.0,
 8.0,
 9.0,
 12.0,
 13.0,
 9.0,
 11.0,
 7.0,
 11.0,
 8.0,
 8.0,
 10.0,
 10.0,
 11.0,
 11.0,
 10.0,
 11.0,
 13.0,
 8.0,
 10.0,
 6.0,
 10.0,
 7.0,
 11.0,
 7.0,
 11.0,
 7.0,
 10.0,
 10.0,
 9.0,
 8.0,
 11.0,
 9.0,
 8.0,
 6.0,
 8.0,
 10.0,
 13.0,
 7.0,
 11.0,
 13.0,
 11.0,
 7.0,
 12.0,
 11.0,
 9.0,
 10.0,
 11.0,
 9.0,
 9.0,
 8.0,
 9.0,
 9.0,
 7.0,
 9.0,
 10.0,
 12.0,
 10.0,
 9.0,
 10.0,
 10.0,
 6.0,
 9.0,
 9.0,
 10.0,
 9.0,
 12.0,
 10.0,
 8.0,
 13.0,
 7.0,
 9.0,
 8.0,
 8.0,
 10.0,
 10.0,
 10.0,
 9.0,
 9.0,
 10.0,
 9.0,
 10.0,
 8.0,
 9.0,
 10.0,
 8.0,
 9.0,
 9.0,
 8.0,
 5.0,
 8.0,
 10.0,
 9.0,
 7.0,
 8.0,
 6.0,
 11.0,
 8.0,
 8.0,
 9.0,
 7.0,
 10.0,
 10.0,
 12.0,
 10.0,
 8.0,
 5.0,
 10.0,
 7.0,
 9.0,
 9.0,
 10.0,
 9

In [ ]:
# plot the histogram

In [43]:
np.fromstring('3,3,', dtype=float, sep=',')

array([3., 3.])